"""add parameters to AI Task

Revision ID: 1d2e35a2d7a6
Revises: 96883c958b15
Create Date: 2025-12-24 02:43:59.257378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d2e35a2d7a6"
down_revision: Union[str, Sequence[str], None] = "96883c958b15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_task", sa.Column("arguments", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_task", "arguments")
    # ### end Alembic commands ###
