"""initial schema

Revision ID: 96883c958b15
Revises:
Create Date: 2025-12-20 04:09:00.148861

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "96883c958b15"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "stock",
        sa.Column("ticker", sa.String(length=4), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("reference_price", sa.Float(), nullable=True),
        sa.Column("reference_price_at", sa.DateTime(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("previous_rank", sa.Integer(), nullable=True),
        sa.Column("change_rank", sa.Integer(), nullable=True),
        sa.Column("previous_change_rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_table(
        "ai_task",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column(
            "task_type",
            sa.Enum("DESCRIPTION", "IMAGE", "VIDEO", name="tasktype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column(
            "image_type",
            sa.Enum("MAIN", "LOGO", "BILLBOARD", "WEBSITE", name="imagetype"),
            nullable=True,
        ),
        sa.Column("atlascloud_id", sa.String(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["ticker"], ["stock.ticker"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_task_ticker"), "ai_task", ["ticker"], unique=False)
    op.create_table(
        "price_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum(
                "INITIAL",
                "SWIPE_UP",
                "SWIPE_DOWN",
                "RANDOM",
                "ADMIN",
                name="changetype",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["ticker"], ["stock.ticker"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_event_ticker"), "price_event", ["ticker"], unique=False
    )
    op.create_table(
        "stock_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["ticker"], ["stock.ticker"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_snapshot_ticker"), "stock_snapshot", ["ticker"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_snapshot_ticker"), table_name="stock_snapshot")
    op.drop_table("stock_snapshot")
    op.drop_index(op.f("ix_price_event_ticker"), table_name="price_event")
    op.drop_table("price_event")
    op.drop_index(op.f("ix_ai_task_ticker"), table_name="ai_task")
    op.drop_table("ai_task")
    op.drop_table("stock")
    # ### end Alembic commands ###
